
#ifndef NTAPITYPES_H
#define NTAPITYPES_H

typedef enum _MEMORY_INFORMATION_CLASS
{
    MemoryBasicInformation,
} MEMORY_INFORMATION_CLASS;
typedef enum _SYSTEM_INFORMATION_CLASS
{
    SystemBasicInformation, 
    SystemProcessorInformation, 
    SystemPerformanceInformation, 
    SystemTimeOfDayInformation, 
    SystemPathInformation, 
    SystemProcessInformation, 
    SystemCallCountInformation, 
    SystemDeviceInformation, 
    SystemProcessorPerformanceInformation, 
    SystemFlagsInformation, 
    SystemCallTimeInformation, 
    SystemModuleInformation, 
    SystemLocksInformation, 
    SystemStackTraceInformation, 
    SystemPagedPoolInformation, 
    SystemNonPagedPoolInformation, 
    SystemHandleInformation, 
    SystemObjectInformation, 
    SystemPageFileInformation, 
    SystemVdmInstemulInformation, 
    SystemVdmBopInformation, 
    SystemFileCacheInformation, 
    SystemPoolTagInformation, 
    SystemInterruptInformation, 
    SystemDpcBehaviorInformation, 
    SystemFullMemoryInformation, 
    SystemLoadGdiDriverInformation, 
    SystemUnloadGdiDriverInformation, 
    SystemTimeAdjustmentInformation, 
    SystemSummaryMemoryInformation, 
    SystemMirrorMemoryInformation, 
    SystemPerformanceTraceInformation, 
    SystemObsolete0, 
    SystemExceptionInformation, 
    SystemCrashDumpStateInformation, 
    SystemKernelDebuggerInformation, 
    SystemContextSwitchInformation, 
    SystemRegistryQuotaInformation, 
    SystemExtendServiceTableInformation, 
    SystemPrioritySeperation, 
    SystemVerifierAddDriverInformation, 
    SystemVerifierRemoveDriverInformation, 
    SystemProcessorIdleInformation, 
    SystemLegacyDriverInformation, 
    SystemCurrentTimeZoneInformation, 
    SystemLookasideInformation, 
    SystemTimeSlipNotification, 
    SystemSessionCreate, 
    SystemSessionDetach, 
    SystemSessionInformation, 
    SystemRangeStartInformation, 
    SystemVerifierInformation, 
    SystemVerifierThunkExtend, 
    SystemSessionProcessInformation, 
    SystemLoadGdiDriverInSystemSpace, 
    SystemNumaProcessorMap, 
    SystemPrefetcherInformation, 
    SystemExtendedProcessInformation, 
    SystemRecommendedSharedDataAlignment, 
    SystemComPlusPackage, 
    SystemNumaAvailableMemory, 
    SystemProcessorPowerInformation, 
    SystemEmulationBasicInformation, 
    SystemEmulationProcessorInformation, 
    SystemExtendedHandleInformation, 
    SystemLostDelayedWriteInformation, 
    SystemBigPoolInformation, 
    SystemSessionPoolTagInformation, 
    SystemSessionMappedViewInformation, 
    SystemHotpatchInformation, 
    SystemObjectSecurityMode, 
    SystemWatchdogTimerHandler, 
    SystemWatchdogTimerInformation, 
    SystemLogicalProcessorInformation, 
    SystemWow64SharedInformationObsolete, 
    SystemRegisterFirmwareTableInformationHandler, 
    SystemFirmwareTableInformation, 
    SystemModuleInformationEx, 
    SystemVerifierTriageInformation, 
    SystemSuperfetchInformation, 
    SystemMemoryListInformation, 
    SystemFileCacheInformationEx, 
    SystemThreadPriorityClientIdInformation, 
    SystemProcessorIdleCycleTimeInformation, 
    SystemVerifierCancellationInformation, 
    SystemProcessorPowerInformationEx, 
    SystemRefTraceInformation, 
    SystemSpecialPoolInformation, 
    SystemProcessIdInformation, 
    SystemErrorPortInformation, 
    SystemBootEnvironmentInformation, 
    SystemHypervisorInformation, 
    SystemVerifierInformationEx, 
    SystemTimeZoneInformation, 
    SystemImageFileExecutionOptionsInformation, 
    SystemCoverageInformation, 
    SystemPrefetchPatchInformation, 
    SystemVerifierFaultsInformation, 
    SystemSystemPartitionInformation, 
    SystemSystemDiskInformation, 
    SystemProcessorPerformanceDistribution, 
    SystemNumaProximityNodeInformation, 
    SystemDynamicTimeZoneInformation, 
    SystemCodeIntegrityInformation, 
    SystemProcessorMicrocodeUpdateInformation, 
    SystemProcessorBrandString, 
    SystemVirtualAddressInformation, 
    SystemLogicalProcessorAndGroupInformation, 
    SystemProcessorCycleTimeInformation, 
    SystemStoreInformation, 
    SystemRegistryAppendString, 
    SystemAitSamplingValue, 
    SystemVhdBootInformation, 
    SystemCpuQuotaInformation, 
    SystemNativeBasicInformation, 
    SystemErrorPortTimeouts, 
    SystemLowPriorityIoInformation, 
    SystemTpmBootEntropyInformation, 
    SystemVerifierCountersInformation, 
    SystemPagedPoolInformationEx, 
    SystemSystemPtesInformationEx, 
    SystemNodeDistanceInformation, 
    SystemAcpiAuditInformation, 
    SystemBasicPerformanceInformation, 
    SystemQueryPerformanceCounterInformation, 
    SystemSessionBigPoolInformation, 
    SystemBootGraphicsInformation, 
    SystemScrubPhysicalMemoryInformation, 
    SystemBadPageInformation,
    SystemProcessorProfileControlArea, 
    SystemCombinePhysicalMemoryInformation, 
    SystemEntropyInterruptTimingInformation, 
    SystemConsoleInformation, 
    SystemPlatformBinaryInformation, 
    SystemPolicyInformation, 
    SystemHypervisorProcessorCountInformation, 
    SystemDeviceDataInformation, 
    SystemDeviceDataEnumerationInformation, 
    SystemMemoryTopologyInformation, 
    SystemMemoryChannelInformation, 
    SystemBootLogoInformation, 
    SystemProcessorPerformanceInformationEx, 
    SystemCriticalProcessErrorLogInformation,
    SystemSecureBootPolicyInformation, 
    SystemPageFileInformationEx, 
    SystemSecureBootInformation, 
    SystemEntropyInterruptTimingRawInformation,
    SystemPortableWorkspaceEfiLauncherInformation, 
    SystemFullProcessInformation, 
    SystemKernelDebuggerInformationEx, 
    SystemBootMetadataInformation, 
    SystemSoftRebootInformation, 
    SystemElamCertificateInformation, 
    SystemOfflineDumpConfigInformation, 
    SystemProcessorFeaturesInformation, 
    SystemRegistryReconciliationInformation, 
    SystemEdidInformation, 
    SystemManufacturingInformation, 
    SystemEnergyEstimationConfigInformation, 
    SystemHypervisorDetailInformation, 
    SystemProcessorCycleStatsInformation, 
    SystemVmGenerationCountInformation,
    SystemTrustedPlatformModuleInformation, 
    SystemKernelDebuggerFlags, 
    SystemCodeIntegrityPolicyInformation, 
    SystemIsolatedUserModeInformation, 
    SystemHardwareSecurityTestInterfaceResultsInformation,
    SystemSingleModuleInformation, 
    SystemAllowedCpuSetsInformation, 
    SystemVsmProtectionInformation, 
    SystemInterruptCpuSetsInformation, 
    SystemSecureBootPolicyFullInformation, 
    SystemCodeIntegrityPolicyFullInformation,
    SystemAffinitizedInterruptProcessorInformation, 
    SystemRootSiloInformation, 
    SystemCpuSetInformation, 
    SystemCpuSetTagInformation, 
    SystemWin32WerStartCallout,
    SystemSecureKernelProfileInformation, 
    SystemCodeIntegrityPlatformManifestInformation, 
    SystemInterruptSteeringInformation, 
    SystemSupportedProcessorArchitectures, 
    SystemMemoryUsageInformation, 
    SystemCodeIntegrityCertificateInformation, 
    SystemPhysicalMemoryInformation, 
    SystemControlFlowTransition, 
    SystemKernelDebuggingAllowed, 
    SystemActivityModerationExeState, 
    SystemActivityModerationUserSettings, 
    SystemCodeIntegrityPoliciesFullInformation,
    SystemCodeIntegrityUnlockInformation, 
    SystemIntegrityQuotaInformation,
    SystemFlushInformation, 
    SystemProcessorIdleMaskInformation, 
    SystemSecureDumpEncryptionInformation,
    SystemWriteConstraintInformation, 
    SystemKernelVaShadowInformation, 
    SystemHypervisorSharedPageInformation, 
    SystemFirmwareBootPerformanceInformation,
    SystemCodeIntegrityVerificationInformation, 
    SystemFirmwarePartitionInformation, 
    SystemSpeculationControlInformation, 
    SystemDmaGuardPolicyInformation, 
    SystemEnclaveLaunchControlInformation, 
    SystemWorkloadAllowedCpuSetsInformation, 
    SystemCodeIntegrityUnlockModeInformation, 
    SystemLeapSecondInformation, 
    SystemFlags2Information, 
    SystemSecurityModelInformation, 
    SystemCodeIntegritySyntheticCacheInformation,
    SystemFeatureConfigurationInformation, 
    SystemFeatureConfigurationSectionInformation, 
    SystemFeatureUsageSubscriptionInformation, 
    SystemSecureSpeculationControlInformation, 
    SystemSpacesBootInformation, 
    SystemFwRamdiskInformation, 
    SystemWheaIpmiHardwareInformation,
    SystemDifSetRuleClassInformation, 
    SystemDifClearRuleClassInformation,
    SystemDifApplyPluginVerificationOnDriver, 
    SystemDifRemovePluginVerificationOnDriver, 
    SystemShadowStackInformation, 
    SystemBuildVersionInformation, 
    SystemPoolLimitInformation, 
    SystemCodeIntegrityAddDynamicStore,
    SystemCodeIntegrityClearDynamicStores,
    SystemDifPoolTrackingInformation,
    SystemPoolZeroingInformation, 
    SystemDpcWatchdogInformation, 
    SystemDpcWatchdogInformation2, 
    SystemSupportedProcessorArchitectures2, 
    SystemSingleProcessorRelationshipInformation, 
    SystemXfgCheckFailureInformation, 
    SystemIommuStateInformation, 
    SystemHypervisorMinrootInformation, 
    SystemHypervisorBootPagesInformation, 
    SystemPointerAuthInformation, 
    SystemSecureKernelDebuggerInformation,
    SystemOriginalImageFeatureInformation, 
    MaxSystemInfoClass
} SYSTEM_INFORMATION_CLASS;
typedef enum _THREADINFOCLASS
{
    ThreadBasicInformation,
    ThreadTimes,
    ThreadPriority,
    ThreadBasePriority,
    ThreadAffinityMask,
    ThreadImpersonationToken,
    ThreadDescriptorTableEntry,
    ThreadEnableAlignmentFaultFixup,
    ThreadEventPair,
    ThreadQuerySetWin32StartAddress,
    ThreadZeroTlsCell,
    ThreadPerformanceCount,
    ThreadAmILastThread,
    ThreadIdealProcessor,
    ThreadPriorityBoost,
    ThreadSetTlsArrayAddress,
    ThreadIsIoPending,
    ThreadHideFromDebugger,
    ThreadBreakOnTermination,
    ThreadSwitchLegacyState,
    ThreadIsTerminated,
    ThreadLastSystemCall,
    ThreadIoPriority,
    ThreadCycleTime,
    ThreadPagePriority,
    ThreadActualBasePriority,
    ThreadTebInformation,
    ThreadCSwitchMon,
    ThreadCSwitchPmu,
    ThreadWow64Context,
    ThreadGroupInformation,
    ThreadUmsInformation,
    ThreadCounterProfiling,
    ThreadIdealProcessorEx,
    ThreadCpuAccountingInformation,
    ThreadSuspendCount,
    ThreadHeterogeneousCpuPolicy,
    ThreadContainerId,
    ThreadNameInformation,
    ThreadSelectedCpuSets,
    ThreadSystemThreadInformation,
    ThreadActualGroupAffinity,
    ThreadDynamicCodePolicyInfo,
    ThreadExplicitCaseSensitivity,
    ThreadWorkOnBehalfTicket,
    ThreadSubsystemInformation,
    ThreadDbgkWerReportActive,
    ThreadAttachContainer,
    ThreadManageWritesToExecutableMemory,
    ThreadPowerThrottlingState,
    ThreadWorkloadClass,
    ThreadCreateStateChange,
    ThreadApplyStateChange,
    ThreadStrongerBadHandleChecks,
    ThreadEffectiveIoPriority,
    ThreadEffectivePagePriority,
    MaxThreadInfoClass
} THREADINFOCLASS;

typedef NTSYSCALLAPI NTSTATUS(NTAPI* NtQueryVirtualMemory_t)(
    _In_ HANDLE ProcessHandle,
    _In_opt_ PVOID BaseAddress,
    _In_ MEMORY_INFORMATION_CLASS MemoryInformationClass,
    _Out_writes_bytes_(MemoryInformationLength) PVOID MemoryInformation,
    _In_ SIZE_T MemoryInformationLength,
    _Out_opt_ PSIZE_T ReturnLength
);

typedef NTSYSCALLAPI NTSTATUS(NTAPI* NtProtectVirtualMemory_t)(
    _In_ HANDLE ProcessHandle,
    _Inout_ PVOID* BaseAddress,
    _Inout_ PSIZE_T RegionSize,
    _In_ ULONG NewProtect,
    _Out_ PULONG OldProtect
);

typedef NTSYSCALLAPI NTSTATUS(NTAPI* NtQuerySystemInformation_t)(
    _In_ SYSTEM_INFORMATION_CLASS SystemInformationClass,
    _Out_writes_bytes_opt_(SystemInformationLength) PVOID SystemInformation,
    _In_ ULONG SystemInformationLength,
    _Out_opt_ PULONG ReturnLength
);

typedef NTSYSCALLAPI NTSTATUS(NTAPI* NtQueryInformationThread_t)(
    _In_ HANDLE ThreadHandle,
    _In_ THREADINFOCLASS ThreadInformationClass,
    _Out_writes_bytes_(ThreadInformationLength) PVOID ThreadInformation,
    _In_ ULONG ThreadInformationLength,
    _Out_opt_ PULONG ReturnLength
);


#endif